(ns stock-levels.core
  (:require
   [reagent.core :as reagent :refer [atom]]
   [reagent.dom :as rdom]
   [reagent.session :as session]
   [reitit.frontend :as reitit]
   [clerk.core :as clerk]
   [accountant.core :as accountant]))

;; -------------------------
;; Routes

(def router
  (reitit/router
   [["/" :index]
    ["/items"
     ["" :items]
     ["/:item-id" :item]]
    ["/about" :about]]))

(defn path-for [route & [params]]
  (if params
    (:path (reitit/match-by-name router route params))
    (:path (reitit/match-by-name router route))))

;; -------------------------
;; Page components

(def app-state (reagent/atom {:item-stock-list [{:item-id "A" :quantity 1} {:item-id "B" :quantity 1} {:item-id "C" :quantity 2}]}))

(defn get-item-stock-list!
  []
  (:item-stock-list @app-state))

(defn update-stock! [f & args]
  (apply swap! app-state update-in [:item-stock-list] f args))

(defn add-stock! [{:keys [item-id quantity] :as update}]
  (update-stock! (fn [item-stock-list]
                       (vec (map #(if (= (:item-id %) "A")
                                    (update-in % [:quantity] + quantity) %)
                                  item-stock-list)))
                    update))

(defn atom-file [file]
  [:input {:type "file"
           :value @file
           :on-change #(reset! file (-> % .-target .-value))}])

;; (defn read-file [event]
;;   (let [reader (js/FileReader.)]
;;     #(reset! event (-> % .-target .-value))
;;     (println (.readAsText reader (-> event .-target .-files (first))))))

(defn submit-file [file]
  (let [reader (js/FileReader.)]
    (.readAsText reader file)
    (println "Submitted!" file)))

(defn item [{:keys [item-id quantity]}]
  [:li {:name item-id :key item-id}
   [:span (str item-id ": " quantity)]])

(defn main []
  (let [file (reagent/atom "")]
    (fn []
      [:div
        [atom-file file]
        [:input {:type "button" :value "increment stock" :on-click #(add-stock! {:item-id "A" :quantity 1})}]
        [:h4 "Item Stock"]
        [:ul {:id "stock-list-items"}
          (for [i (:item-stock-list @app-state)]
            [item i])]])))

(defn home-page []
  (fn []
    [:span.main
      [:h1 "Stock Management"]
      [:h5 "Import instruction feed:"]
      [:div
        [main]
      ]
    ]
  ))

(defn items-page []
  (fn []
    [:span.main
     [:h1 "The items of stock-levels"]
     [:ul {:id "stock-list-items"} (map (fn [item-id]
                 [:li {:name (str "item-" item-id) :key (str "item-" item-id)}
                  [:a {:href (path-for :item {:item-id item-id})} "Item: " item-id]])
               (range 1 60))]]))


(defn item-page []
  (fn []
    (let [routing-data (session/get :route)
          item (get-in routing-data [:route-params :item-id])]
      [:span.main
       [:h1 (str "Item " item " of stock-levels")]
       [:p [:a {:href (path-for :items)} "Back to the list of items"]]])))


(defn about-page []
  (fn [] [:span.main
          [:h1 "About stock-levels"]]))


;; -------------------------
;; Translate routes -> page components

(defn page-for [route]
  (case route
    :index #'home-page
    :about #'about-page
    :items #'items-page
    :item #'item-page))


;; -------------------------
;; Page mounting component

(defn current-page []
  (fn []
    (let [page (:current-page (session/get :route))]
      [:div
       [:header
        [:p [:a {:href (path-for :index)} "Home"] " | "
         [:a {:href (path-for :about)} "About stock-levels"]]]
       [page]
       [:footer
        [:p "stock-levels was generated by the "
         [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]]])))

;; -------------------------
;; Initialize app

(defn mount-root []
  (rdom/render [current-page] (.getElementById js/document "app")))

(defn init! []
  (clerk/initialize!)
  (accountant/configure-navigation!
   {:nav-handler
    (fn [path]
      (let [match (reitit/match-by-path router path)
            current-page (:name (:data  match))
            route-params (:path-params match)]
        (reagent/after-render clerk/after-render!)
        (session/put! :route {:current-page (page-for current-page)
                              :route-params route-params})
        (clerk/navigate-page! path)
        ))
    :path-exists?
    (fn [path]
      (boolean (reitit/match-by-path router path)))})
  (accountant/dispatch-current!)
  (mount-root))

